apiVersion: apps/v1
kind: Deployment
metadata:
  name: fp/springboot
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fp/springboot
  template:
    metadata:
      labels:
        app: fp/springboot
    spec:
      containers:
        - name: fp/springboot
          image: fp/springboot
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: fp/springboot
spec:
  selector:
    app: fp/springboot
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
