# src/main/resources/application.yml
spring:
  security:
    oauth2:
      client:
        registration:
          auth0:

            client-id: YMKcoQEU2VeWgKlvfImLU2M0mjXn3gvc
            client-secret: SUPERSECRET


            scope:
              - openid
              - profile
              - email
        provider:
          auth0:
            # trailing slash is important!

            issuer-uri: https://dev-35n2stap.auth0.com/

